name: latent-space-repr-el-market-curves
channels:
  - conda-forge
dependencies:
  - python=3.9.19
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - jupytext
  - lightning
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pytorch
  - scikit-learn
  - torchmetrics
  - ruff
  - u8darts-all
  - umap-learn
  - pip:
    - polars
    - python-dotenv
    - mkdocs
    - ray[data,train,tune,serve]
    - -e .